[package]
name = "uair"
version = "0.3.1"
authors = ["Rishabh Das <rdas@tutanota.com>"]
edition = "2021"
description = "An extensible pomodoro timer"
license = "MIT"
repository = "https://github.com/metent/uair/"
keywords = ["pomodoro", "timer", "countdown", "cli", "productivity"]
categories = ["command-line-utilities"]

[dependencies]
anyhow = "1.0.58"
async-io = "1.7.0"
async-net = "1.6.1"
bincode = "1.3.3"
futures-lite = "1.12.0"
gumdrop = "0.8.1"
humantime = "2.1.0"
humantime-serde = "1.1.1"
serde = { version = "1.0.139", features = ["derive"] }
signal-hook = "0.3.14"
signal-hook-async-std = "0.2.2"
toml = "0.5.9"
